### ISSUE TITLE
mint upload still active? I cant find it on my install

### ISSUE THREAD

**Issue by odarcan** [linuxmint/doc-developer-guide#24]
https://linuxmint-developer-guide.readthedocs.io/en/latest/mint-tools.html#mintupload

perhaps it should be removed I dont know if the tool has been discontinued,

thanks

**Comment by mtwebster** [comment]
It's still available, just not part of the default installation anymore.

We periodically review default apps, and occasionally remove ones we don't think are used much - mintupload is a very niche tool. For a vast majority of users it was just start menu bloat.

You can install it with `apt install mintupload` or using the software manager.
